### ISSUE TITLE
Needs to support hot reloading when running in Docker container

### ISSUE THREAD

**Issue by nbeck415** [nbeck415/bun-nextjs-dockerized#1]

**Comment by Sasha95** [comment]
docker-compose.yml

```
version: '3.8'

services:
  next:
    labels:
      shipyard.route: '/'
    build:
      context: .
    ports:
      - '3000:3000'
    volumes:
      - ./public:/app/public
      - ./src:/app/src
    develop:
      watch:
        - action: sync
          path: ./public
          target: /app/public
        - action: sync
          path: ./src
          target: /app/src
        - action: rebuild
          path: package.json
```
