### ISSUE TITLE
how do you handle env vars and secrets 

### ISSUE THREAD

**Issue by romelgomez** [nbeck415/bun-nextjs-dockerized#2]
let say I wanna upload this to a register like ghcr, how to set/build this docker with thoses vars ?

**Comment by romelgomez** [comment]
I have a Next.js app that is deployed using Docker. In the repository, I set two secret environment variables. After deploying the build to Railway, I attempted to log these environment variables in the view, but they are coming up as undefined.

 


```yaml
# https://docs.github.com/en/actions
# https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions

name: WEB CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm i

      - name: Build
        run: npx next build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/next-docker:latest
          build-args: |
            NEXT_PUBLIC_GRAPHQL: ${{ secrets.NEXT_PUBLIC_GRAPHQL }}
            TAG_ID: ${{ secrets.TAG_ID }}

```


```Dockerfile
FROM node:20-alpine AS base

ARG TAG_ID
ARG NEXT_PUBLIC_GRAPHQL

ENV NEXT_PUBLIC_GRAPHQL=$NEXT_PUBLIC_GRAPHQL
ENV TAG_ID=$TAG_ID

WORKDIR /app

COPY package*.json ./

RUN npm i

COPY . .

EXPOSE 3000

ENV PORT 3000

ENV NEXT_TELEMETRY_DISABLED=1

CMD ["npx", "next", "start"]

```
